### ISSUE TITLE
Class folder in default classpath

### ISSUE THREAD

**Issue by gstacey** [jmhofer/eCobertura#5] opened 2010-06-18 01:42 UTC
If there is a class folder in your classpath the plugin seems to process it as the output folder.  The behavior I am seeing is that it just copies the contents of the class folder to it's workspace directory rather than instrumenting the classes from the project output folder.

The result is that the test(s) don't run and the console shows a ClassNotFoundException for the test class that is being run.

**Comment by jmhofer** [comment] 2010-07-11 09:17
In fact, eCobertura does copy the contents of the output folder into its own workspace and instruments the classes there. - But it should also replace the output folder with its own workspace in the classpath of the launch configuration upon covered launches.

However, obviously, something about this doesn't work as it should under some conditions.

**Comment by jmhofer** [comment] 2010-07-20 20:06
Actually, this should be fixed in 0.9.8 together with the other classpath issue.

**Comment by jmhofer** [comment] 2010-07-27 12:26
Closing this, as it's basically a duplicate of the other classpath issue.

**Closed as completed by jmhofer** 2010-07-27 12:26 UTC
Labels: Classpath
